In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
training_set=pd.read_csv('trainset.csv')


In [4]:
training_set

Date         Open         High          Low        Close  \
0     2013-01-02   357.385559   361.151062   355.959839   359.288177   
1     2013-01-03   360.122742   363.600128   358.031342   359.496826   
2     2013-01-04   362.313507   368.339294   361.488861   366.600616   
3     2013-01-07   365.348755   367.301056   362.929504   365.001007   
4     2013-01-08   365.393463   365.771027   359.874359   364.280701   
5     2013-01-09   363.769043   366.789398   361.945892   366.675140   
6     2013-01-10   369.014923   370.092896   364.380066   368.344269   
7     2013-01-11   368.602600   368.816193   365.771027   367.604095   
8     2013-01-14   366.118744   368.701935   358.841095   359.288177   
9     2013-01-15   357.340851   365.125214   353.749207   360.122742   
10    2013-01-16   358.865936   359.829651   354.529144   355.284210   
11    2013-01-17   356.536072   357.494843   353.212677   353.361725   
12    2013-01-18   352.884827   354.082031   348.398987   349.978729   
13    2013-01-22   350.053253   350.391052   345.512787   349.164032   
14    2013-01-23   365.617004   372.079987   365.517670   368.354218   
15    2013-01-24   368.225037   375.969666   367.862396   374.668152   
16    2013-01-25   372.959259   376.789337   372.700928   374.399902   
17    2013-01-28   373.451050   375.358643   371.528564   372.939392   
18    2013-01-29   370.962250   376.029297   370.857941   374.404846   
19    2013-01-30   374.434662   378.016357   374.022339   374.479370   
20    2013-01-31   372.830109   376.362122   372.700928   375.403351   
21    2013-02-01   376.650238   385.790802   376.600586   385.294037   
22    2013-02-04   381.364594   382.745605   376.685028   377.057617   
23    2013-02-05   378.105774   383.063538   377.281158   380.395905   
24    2013-02-06   377.082428   383.982574   376.799286   382.596588   
25    2013-02-07   382.363098   386.888672   380.276672   384.474365   
26    2013-02-08   387.544403   390.793274   387.261230   390.147461   
27    2013-02-11   386.684998   388.970123   384.375000   388.682007   
28    2013-02-12   388.349152   391.404297   387.166840   387.827545   
29    2013-02-13   387.544403   390.137543   387.464905   388.900574   
...          ...          ...          ...          ...          ...   
1229  2017-11-16  1022.520020  1035.920044  1022.520020  1032.500000   
1230  2017-11-17  1034.010010  1034.420044  1017.750000  1019.090027   
1231  2017-11-20  1020.260010  1022.609985  1017.500000  1018.380005   
1232  2017-11-21  1023.309998  1035.109985  1022.655029  1034.489990   
1233  2017-11-22  1035.000000  1039.706055  1031.430054  1035.959961   
1234  2017-11-24  1035.869995  1043.177979  1035.000000  1040.609985   
1235  2017-11-27  1040.000000  1055.459961  1038.439941  1054.209961   
1236  2017-11-28  1055.089966  1062.375000  1040.000000  1047.410034   
1237  2017-11-29  1042.680054  1044.079956  1015.650024  1021.659973   
1238  2017-11-30  1022.369995  1028.489990  1015.000000  1021.409973   
1239  2017-12-01  1015.799988  1022.489990  1002.020020  1010.169983   
1240  2017-12-04  1012.659973  1016.099976   995.570007   998.679993   
1241  2017-12-05   995.940002  1020.609985   988.280029  1005.150024   
1242  2017-12-06  1001.500000  1024.969971  1001.140015  1018.380005   
1243  2017-12-07  1020.429993  1034.239990  1018.070984  1030.930054   
1244  2017-12-08  1037.489990  1042.050049  1032.521973  1037.050049   
1245  2017-12-11  1035.500000  1043.800049  1032.050049  1041.099976   
1246  2017-12-12  1039.630005  1050.310059  1033.689941  1040.479980   
1247  2017-12-13  1046.119995  1046.665039  1038.380005  1040.609985   
1248  2017-12-14  1045.000000  1058.500000  1043.109985  1049.150024   
1249  2017-12-15  1054.609985  1067.619995  1049.500000  1064.189941   
1250  2017-12-18  1066.079956  1078.489990  1062.000000  1077.140015   
1251  2017-12-19  1075.199951  1076.839966  1063.550049  1070.680054   
1252  2017-12-20  1071.780029  1073.380005  1061.520

In [5]:
training_set=training_set.iloc[:,1:2].values

In [6]:
training_set

array([[ 357.385559],
       [ 360.122742],
       [ 362.313507],
       ...,
       [1057.390015],
       [1051.599976],
       [1046.719971]])

In [7]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler()
training_set=sc.fit_transform(training_set)

In [8]:
X_train= training_set[0:1257]
y_train= training_set[1:1258]

In [9]:
X_train

array([[0.01011148],
       [0.01388614],
       [0.01690727],
       ...,
       [0.9805695 ],
       [0.97637719],
       [0.97543954]])

In [10]:
X_train=np.reshape(X_train, (1257 , 1 , 1))


In [11]:
X_train

array([[[0.01011148]],

       [[0.01388614]],

       [[0.01690727]],

       ...,

       [[0.9805695 ]],

       [[0.97637719]],

       [[0.97543954]]])

In [12]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


In [13]:
regressor = Sequential()

In [14]:
regressor.add(LSTM(units=4, activation= 'sigmoid', input_shape= (None,1)))

In [15]:
regressor.add(Dense( units=1 ))

In [16]:
regressor.compile(optimizer='adam', loss='mean_squared_error')

In [17]:
regressor.fit(X_train, y_train, batch_size=32, epochs=200)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/200
1257/1257 [==============================] - 22s 18ms/step - loss: 0.6155
Epoch 2/200
1257/1257 [==============================] - 0s 165us/step - loss: 0.4738
Epoch 3/200
1257/1257 [==============================] - 0s 158us/step - loss: 0.3616
Epoch 4/200
1257/1257 [==============================] - 0s 170us/step - loss: 0.2750
Epoch 5/200
1257/1257 [==============================] - 0s 168us/step - loss: 0.2089
Epoch 6/200
1257/1257 [==============================] - 0s 166us/step - loss: 0.1591
Epoch 7/200
1257/1257 [==============================] - 0s 168us/step - loss: 0.1227
Epoch 8/200
1257/1257 [==============================] - 0s 159us/step - loss: 0.0964
Epoch 9/200
1257/1257 [==============================] - 0s 160us/step - loss: 0.0779
Epoch 10/200
1257/1257 [==============================] - 0s 167us/step - loss: 0.0653
Epoch 11/200
1257/1257 [===================

Epoch 87/200
1257/1257 [==============================] - 0s 222us/step - loss: 0.0020
Epoch 88/200
1257/1257 [==============================] - 0s 213us/step - loss: 0.0018
Epoch 89/200
1257/1257 [==============================] - 0s 251us/step - loss: 0.0016
Epoch 90/200
1257/1257 [==============================] - 0s 251us/step - loss: 0.0015
Epoch 91/200
1257/1257 [==============================] - 0s 167us/step - loss: 0.0013
Epoch 92/200
1257/1257 [==============================] - 0s 153us/step - loss: 0.0012
Epoch 93/200
1257/1257 [==============================] - 0s 152us/step - loss: 0.0011
Epoch 94/200
1257/1257 [==============================] - 0s 157us/step - loss: 9.5789e-04
Epoch 95/200
1257/1257 [==============================] - 0s 149us/step - loss: 8.6043e-04
Epoch 96/200
1257/1257 [==============================] - 0s 152us/step - loss: 7.7380e-04
Epoch 97/200
1257/1257 [==============================] - 0s 149us/step - loss: 6.9601e-04
Epoch 98/200
1257/1257 [===

1257/1257 [==============================] - 0s 230us/step - loss: 1.6572e-04
Epoch 177/200
1257/1257 [==============================] - 0s 229us/step - loss: 1.6536e-04
Epoch 178/200
1257/1257 [==============================] - 0s 231us/step - loss: 1.6538e-04
Epoch 179/200
1257/1257 [==============================] - 0s 230us/step - loss: 1.6496e-04
Epoch 180/200
1257/1257 [==============================] - 0s 227us/step - loss: 1.6699e-04
Epoch 181/200
1257/1257 [==============================] - 0s 229us/step - loss: 1.6536e-04
Epoch 182/200
1257/1257 [==============================] - 0s 225us/step - loss: 1.6444e-04
Epoch 183/200
1257/1257 [==============================] - 0s 223us/step - loss: 1.6488e-04
Epoch 184/200
1257/1257 [==============================] - 0s 309us/step - loss: 1.6490e-04
Epoch 185/200
1257/1257 [==============================] - 0s 341us/step - loss: 1.6432e-04
Epoch 186/200
1257/1257 [==============================] - 0s 345us/step - loss: 1.6696e-04
Ep

In [20]:
# Geting the real stock price of 2017
test_set = pd.read_csv('testset.csv')
real_stock_price = test_set.iloc[:,1:2].values


In [21]:
real_stock_price

array([[1048.339966],
       [1064.310059],
       [1088.      ],
       [1094.      ],
       [1102.22998 ],
       [1109.400024],
       [1097.099976],
       [1106.300049],
       [1102.410034],
       [1132.51001 ],
       [1126.219971],
       [1131.410034],
       [1131.829956],
       [1137.48999 ],
       [1159.849976],
       [1177.329956],
       [1172.530029],
       [1175.079956],
       [1176.47998 ],
       [1167.829956],
       [1170.569946],
       [1162.609985],
       [1122.      ],
       [1090.599976],
       [1027.180054],
       [1081.540039],
       [1055.410034],
       [1017.25    ],
       [1048.      ],
       [1045.      ],
       [1048.949951],
       [1079.069946],
       [1088.410034],
       [1090.569946],
       [1106.469971],
       [1116.189941],
       [1112.640015],
       [1127.800049],
       [1141.23999 ],
       [1123.030029],
       [1107.869995],
       [1053.079956],
       [1075.140015],
       [1099.219971],
       [1089.189941],
       [11

In [22]:
test_set

Date         Open         High          Low        Close  \
0    2018-01-02  1048.339966  1066.939941  1045.229980  1065.000000   
1    2018-01-03  1064.310059  1086.290039  1063.209961  1082.479980   
2    2018-01-04  1088.000000  1093.569946  1084.001953  1086.400024   
3    2018-01-05  1094.000000  1104.250000  1092.000000  1102.229980   
4    2018-01-08  1102.229980  1111.270020  1101.619995  1106.939941   
5    2018-01-09  1109.400024  1110.569946  1101.230957  1106.260010   
6    2018-01-10  1097.099976  1104.599976  1096.109985  1102.609985   
7    2018-01-11  1106.300049  1106.525024  1099.589966  1105.520020   
8    2018-01-12  1102.410034  1124.290039  1101.150024  1122.260010   
9    2018-01-16  1132.510010  1139.910034  1117.832031  1121.760010   
10   2018-01-17  1126.219971  1132.599976  1117.010010  1131.979980   
11   2018-01-18  1131.410034  1132.510010  1117.500000  1129.790039   
12   2018-01-19  1131.829956  1137.859985  1128.300049  1137.510010   
13   2018-01-22  1137.489990  1159.880005  1135.109985  1155.810059   
14   2018-01-23  1159.849976  1171.626953  1158.750000  1169.969971   
15   2018-01-24  1177.329956  1179.859985  1161.050049  1164.239990   
16   2018-01-25  1172.530029  1175.939941  1162.760010  1170.369995   
17   2018-01-26  1175.079956  1175.839966  1158.109985  1175.839966   
18   2018-01-29  1176.479980  1186.890015  1171.979980  1175.579956   
19   2018-01-30  1167.829956  1176.520020  1163.520020  1163.689941   
20   2018-01-31  1170.569946  1173.000000  1159.130005  1169.939941   
21   2018-02-01  1162.609985  1174.000000  1157.520020  1167.699951   
22   2018-02-02  1122.000000  1123.069946  1107.277954  1111.900024   
23   2018-02-05  1090.599976  1110.000000  1052.030029  1055.800049   
24   2018-02-06  1027.180054  1081.709961  1023.137024  1080.599976   
25   2018-02-07  1081.540039  1081.780029  1048.260010  1048.579956   
26   2018-02-08  1055.410034  1058.619995  1000.659973  1001.520020   
27   2018-02-09  1017.250000  1043.969971   992.559998  1037.780029   
28   2018-02-12  1048.000000  1061.500000  1040.927979  1051.939941   
29   2018-02-13  1045.000000  1058.369995  1044.087036  1052.099976   
..          ...          ...          ...          ...          ...   
95   2018-05-18  1061.859985  1069.939941  1060.680054  1066.359985   
96   2018-05-21  1074.060059  1088.000000  1073.650024  1079.579956   
97   2018-05-22  1083.560059  1086.589966  1066.689941  1069.729980   
98   2018-05-23  1065.130005  1080.780029  1061.709961  1079.689941   
99   2018-05-24  1079.000000  1080.469971  1066.150024  1079.239990   
100  2018-05-25  1079.020020  1082.560059  1073.775024  1075.660034   
101  2018-05-29  1064.890015  1073.369995  1055.219971  1060.319946   
102  2018-05-30  1063.030029  1069.209961  1056.829956  1067.800049   
103  2018-05-31  1067.560059  1097.189941  1067.560059  1084.989990   
104  2018-06-01  1099.349976  1120.000000  1098.500000  1119.500000   
105  2018-06-04  1122.329956  1141.890015  1122.005005  1139.290039   
106  2018-06-05  1140.989990  1145.738037  1133.189941  1139.660034   
107  2018-06-06  1142.170044  1143.000000  1125.743042  1136.880005   
108  2018-06-07  1131.319946  1135.819946  1116.520020  1123.859985   
109  2018-06-08  1118.180054  1126.670044  1112.150024  1120.869995   
110  2018-06-11  1118.599976  1137.260010  1118.599976  1129.989990   
111  2018-06-12  1131.069946  1139.790039  1130.734985  1139.319946   
112  2018-06-13  1141.119995  1146.500000  1133.380005  1134.790039   
113  2018-06-14  1143.849976  1155.469971  1140.640015  1152.119995   
114  2018-06-15  1148.859985  1153.420044  1143.484985  1152.260010   
115  2018-06-18  1143.650024  1174.310059  1143.589966  1173.459961   
116  2018-06-19  1158.500000  1171.270020  1154.010010  1168.060059   
117  2018-06-20  1175.310059  1186.286011  1169.160034  1169.839966   
118  2018-06-21  1174.849976  1177.295044  1152.232056  1157.660034   
119  2018-06-22  1159.140015  1162.

In [23]:

# Geting the Predicted Stock Price of 2017
inputs = real_stock_price

In [24]:
inputs = sc.transform(inputs)

In [33]:
inputs = np.reshape(inputs, (20,1,1))

ValueError: cannot reshape array of size 125 into shape (20,1,1)

In [28]:
predicted_stock_price = regressor.predict(inputs)

ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (125, 1)